export let sampleData = [
  {
    id: "1",
    username: "alexsmith",
    fullName: "Alex Smith",
    email: "alexsmith@gmail.com",
    city: "New York",
    memberSince: "2021-01-15",
  },
  {
    id: "2",
    username: "sarahjohnson",
    fullName: "Sarah Johnson",
    email: "sarahj@yahoo.com",
    city: "Los Angeles",
    memberSince: "2021-02-20",
  },
  {
    id: "3",
    username: "mikebrown",
    fullName: "Mike Brown",
    email: "mikebrown@hotmail.com",
    city: "Chicago",
    memberSince: "2021-03-11",
  },
  {
    id: "4",
    username: "emilyclark",
    fullName: "Emily Clark",
    email: "emilyclark@outlook.com",
    city: "Houston",
    memberSince: "2021-04-05",
  },
  {
    id: "5",
    username: "davidlee",
    fullName: "David Lee",
    email: "davidlee@aol.com",
    city: "Phoenix",
    memberSince: "2021-05-16",
  },
  {
    id: "6",
    username: "lindagarcia",
    fullName: "Linda Garcia",
    email: "lindagarcia@mail.com",
    city: "Philadelphia",
    memberSince: "2021-06-21",
  },
  {
    id: "7",
    username: "brianmartinez",
    fullName: "Brian Martinez",
    email: "brianmartinez@yahoo.co.uk",
    city: "San Antonio",
    memberSince: "2021-07-30",
  },
  {
    id: "8",
    username: "jessicataylor",
    fullName: "Jessica Taylor",
    email: "jessicataylor@gmail.com",
    city: "San Diego",
    memberSince: "2021-08-12",
  },
  {
    id: "9",
    username: "jamesdavis",
    fullName: "James Davis",
    email: "jamesdavis@hotmail.com",
    city: "Dallas",
    memberSince: "2021-09-18",
  },
  {
    id: "10",
    username: "amandawilson",
    fullName: "Amanda Wilson",
    email: "amandawilson@protonmail.com",
    city: "San Jose",
    memberSince: "2021-10-23",
  },
  {
    id: "11",
    username: "robertmoore",
    fullName: "Robert Moore",
    email: "robertmoore@icloud.com",
    city: "Austin",
    memberSince: "2021-11-05",
  },
  {
    id: "12",
    username: "laurajackson",
    fullName: "Laura Jackson",
    email: "laurajackson@yahoo.com",
    city: "Jacksonville",
    memberSince: "2021-12-14",
  },
  {
    id: "13",
    username: "kevinwhite",
    fullName: "Kevin White",
    email: "kevinwhite@gmail.com",
    city: "Fort Worth",
    memberSince: "2022-01-09",
  },
  {
    id: "14",
    username: "sophiaharris",
    fullName: "Sophia Harris",
    email: "sophiaharris@outlook.com",
    city: "Charlotte",
    memberSince: "2022-02-17",
  },
  {
    id: "15",
    username: "danielthompson",
    fullName: "Daniel Thompson",
    email: "danielthompson@aol.com",
    city: "Detroit",
    memberSince: "2022-03-26",
  },
  {
    id: "16",
    username: "megananderson",
    fullName: "Megan Anderson",
    email: "megananderson@mail.com",
    city: "El Paso",
    memberSince: "2022-04-10",
  },
  {
    id: "17",
    username: "chrismartinez",
    fullName: "Chris Martinez",
    email: "chrismartinez@yahoo.co.uk",
    city: "Memphis",
    memberSince: "2022-05-15",
  },
  {
    id: "18",
    username: "ashleythomas",
    fullName: "Ashley Thomas",
    email: "ashleythomas@gmail.com",
    city: "Baltimore",
    memberSince: "2022-06-19",
  },
  {
    id: "19",
    username: "johncarter",
    fullName: "John Carter",
    email: "johncarter@hotmail.com",
    city: "Boston",
    memberSince: "2022-07-22",
  },
  {
    id: "20",
    username: "jenniferlee",
    fullName: "Jennifer Lee",
    email: "jenniferlee@protonmail.com",
    city: "Nashville",
    memberSince: "2022-08-30",
  },
];
