name: Run Cypress Testing

on:
  push:
    branches:
      - main
jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install npm dependencies
      - name: Install Dependencies
        run: npm install

      # Start Development Server
      - name: Start Development Server
        run: npm run dev &
        background: true

      # Wait for the server to be ready (adjust sleep duration based on your server startup time)
      - name: Wait for Server
        run: sleep 20

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
